#The version of the docker-compose file.
version: '3.9'

#Creating a mongo container and setting the root user and password.
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --quiet --logpath /dev/null

#This is creating a backend container and setting the port to 5000.
  backend:
    build: ./
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:example@mongo:27017/myapp
